spring:
  datasource:  
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true  
    username: root  
    password: 12345678  
    driverClassName: com.mysql.cj.jdbc.Driver  
  jpa:  
    database: MYSQL  
    show-sql: true  
    hibernate:  
      ddl-auto: update  
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        format_sql: true

